package com.alechilles.alecstamework.persistence.operation;

/** Stable phase names used only by constructor-injected persistence fault tests. */
public enum PersistenceCheckpoint {
    BEFORE_AVAILABILITY_ADMISSION,
    AFTER_OPERATION_PREPARATION,
    BEFORE_FIRST_SQL_STATEMENT,
    AFTER_LOGICAL_SQL_MUTATION,
    BEFORE_COMMIT,
    AFTER_COMMIT_RETURN,
    AFTER_CANONICAL_READBACK,
    BEFORE_RUNTIME_INDEX_PUBLICATION,
    AFTER_RUNTIME_INDEX_PUBLICATION,
    BEFORE_LIVE_ENTITY_REMOVAL,
    AFTER_LIVE_ENTITY_REMOVAL,
    BEFORE_LIVE_ENTITY_SPAWN,
    AFTER_LIVE_ENTITY_SPAWN,
    BEFORE_SOURCE_ITEM_FINALIZATION,
    AFTER_SOURCE_ITEM_FINALIZATION,
    BEFORE_JOURNAL_TERMINALIZATION,
    BEFORE_TELEMETRY_DIAGNOSTICS_EMISSION,
    DURING_SHUTDOWN_RESTART_RECONSTRUCTION
}
