package com.alechilles.alecstamework.ui;

import com.alechilles.alecstamework.config.assets.TwGlobalConfig;
import com.alechilles.alecstamework.config.assets.TwNeedsConfig;
import com.alechilles.alecstamework.persistence.TameworkSettingsStore;
import com.alechilles.alecstamework.settings.AnimalAgingMode;
import com.alechilles.alecstamework.settings.ResolvedTameworkSettings;
import javax.annotation.Nonnull;

/**
 * Immutable form-state snapshot for the curated `/tw settings` page.
 */
public record TameworkSettingsValues(int populationLimitPerPlayerOwnedTotal,
                                     @Nonnull TwGlobalConfig.PerPlayerLimitScope populationPerPlayerLimitScope,
                                     boolean simpleClaimsEnabled,
                                     int simpleClaimsLimitPerClaimChunk,
                                     int simpleClaimsLimitPerClaimTotal,
                                     boolean simpleClaimsBreedingRequiresClaim,
                                     boolean simpleClaimsProtectTamedFromNonMembers,
                                     boolean blockOwnerDamage,
                                     boolean blockAllPlayerDamageIfOwned,
                                     boolean invulnerableIfOwned,
                                     boolean captureClearsOwner,
                                     boolean spawnSetsOwner,
                                     boolean captureRequiresOwner,
                                     boolean spawnRequiresOwner,
                                     boolean interactionRequiresOwner,
                                     boolean linkingRequiresOwner,
                                     boolean needsEnabled,
                                     @Nonnull String needsResourceMode,
                                     boolean needsDamageEnabled,
                                     @Nonnull TwNeedsConfig.TickPolicyMode needsTickPolicyMode,
                                     double needsOwnerOfflineGraceHours,
                                     double needsOwnerOfflineDecayMultiplier,
                                     @Nonnull TwNeedsConfig.DamageModel needsDamageModel,
                                     @Nonnull TwNeedsConfig.DualNeedRule needsDamageDualNeedRule,
                                     double needsStarvationDamagePerMinute,
                                     double needsDehydrationDamagePerMinute,
                                     boolean needsDamageLethal,
                                     boolean happinessEnabled,
                                     boolean passiveBreedingEnabled,
                                     boolean breedingRequiresHappiness,
                                     boolean breedingGenderEnabled,
                                     boolean traitsEnabled,
                                     boolean levelingEnabled,
                                     boolean talentsEnabled,
                                     boolean reviveSystemEnabled,
                                     boolean recallTeleportingEnabled,
                                     boolean telemetryEnabled,
                                     boolean telemetryBreadcrumbsEnabled,
                                     @Nonnull AnimalAgingMode animalAgingMode,
                                     boolean animalOldAgeDeathEnabled,
                                     boolean announcementsEnabled,
                                     int commandPanelCardsPerPage) {

    /** Compatibility constructor for callers compiled before command-panel pagination settings. */
    public TameworkSettingsValues(int populationLimitPerPlayerOwnedTotal,
                                  @Nonnull TwGlobalConfig.PerPlayerLimitScope populationPerPlayerLimitScope,
                                  boolean simpleClaimsEnabled,
                                  int simpleClaimsLimitPerClaimChunk,
                                  int simpleClaimsLimitPerClaimTotal,
                                  boolean simpleClaimsBreedingRequiresClaim,
                                  boolean simpleClaimsProtectTamedFromNonMembers,
                                  boolean blockOwnerDamage,
                                  boolean blockAllPlayerDamageIfOwned,
                                  boolean invulnerableIfOwned,
                                  boolean captureClearsOwner,
                                  boolean spawnSetsOwner,
                                  boolean captureRequiresOwner,
                                  boolean spawnRequiresOwner,
                                  boolean interactionRequiresOwner,
                                  boolean linkingRequiresOwner,
                                  boolean needsEnabled,
                                  @Nonnull String needsResourceMode,
                                  boolean needsDamageEnabled,
                                  @Nonnull TwNeedsConfig.TickPolicyMode needsTickPolicyMode,
                                  double needsOwnerOfflineGraceHours,
                                  double needsOwnerOfflineDecayMultiplier,
                                  @Nonnull TwNeedsConfig.DamageModel needsDamageModel,
                                  @Nonnull TwNeedsConfig.DualNeedRule needsDamageDualNeedRule,
                                  double needsStarvationDamagePerMinute,
                                  double needsDehydrationDamagePerMinute,
                                  boolean needsDamageLethal,
                                  boolean happinessEnabled,
                                  boolean passiveBreedingEnabled,
                                  boolean breedingRequiresHappiness,
                                  boolean breedingGenderEnabled,
                                  boolean traitsEnabled,
                                  boolean levelingEnabled,
                                  boolean talentsEnabled,
                                  boolean reviveSystemEnabled,
                                  boolean recallTeleportingEnabled,
                                  boolean telemetryEnabled,
                                  boolean telemetryBreadcrumbsEnabled,
                                  @Nonnull AnimalAgingMode animalAgingMode,
                                  boolean animalOldAgeDeathEnabled,
                                  boolean announcementsEnabled) {
        this(populationLimitPerPlayerOwnedTotal, populationPerPlayerLimitScope, simpleClaimsEnabled,
                simpleClaimsLimitPerClaimChunk, simpleClaimsLimitPerClaimTotal,
                simpleClaimsBreedingRequiresClaim, simpleClaimsProtectTamedFromNonMembers,
                blockOwnerDamage, blockAllPlayerDamageIfOwned, invulnerableIfOwned,
                captureClearsOwner, spawnSetsOwner, captureRequiresOwner, spawnRequiresOwner,
                interactionRequiresOwner, linkingRequiresOwner, needsEnabled, needsResourceMode,
                needsDamageEnabled, needsTickPolicyMode, needsOwnerOfflineGraceHours,
                needsOwnerOfflineDecayMultiplier, needsDamageModel, needsDamageDualNeedRule,
                needsStarvationDamagePerMinute, needsDehydrationDamagePerMinute, needsDamageLethal,
                happinessEnabled, passiveBreedingEnabled, breedingRequiresHappiness, breedingGenderEnabled,
                traitsEnabled, levelingEnabled, talentsEnabled, reviveSystemEnabled,
                recallTeleportingEnabled, telemetryEnabled, telemetryBreadcrumbsEnabled, animalAgingMode,
                animalOldAgeDeathEnabled, announcementsEnabled, 50);
    }

    @Nonnull
    TameworkSettingsStore.GlobalSettingsSnapshot toGlobalSettingsSnapshot() {
        return new TameworkSettingsStore.GlobalSettingsSnapshot(
                populationLimitPerPlayerOwnedTotal,
                populationPerPlayerLimitScope.configValue(),
                simpleClaimsEnabled,
                simpleClaimsLimitPerClaimChunk,
                simpleClaimsLimitPerClaimTotal,
                simpleClaimsBreedingRequiresClaim,
                simpleClaimsProtectTamedFromNonMembers,
                blockOwnerDamage,
                blockAllPlayerDamageIfOwned,
                invulnerableIfOwned,
                captureClearsOwner,
                spawnSetsOwner,
                captureRequiresOwner,
                spawnRequiresOwner,
                interactionRequiresOwner,
                linkingRequiresOwner,
                needsEnabled,
                needsResourceMode,
                needsTickPolicyMode.toConfigValue(),
                needsOwnerOfflineGraceHours,
                needsOwnerOfflineDecayMultiplier,
                needsDamageEnabled,
                needsDamageModel.toConfigValue(),
                needsDamageDualNeedRule.toConfigValue(),
                needsStarvationDamagePerMinute,
                needsDehydrationDamagePerMinute,
                needsDamageLethal,
                happinessEnabled,
                passiveBreedingEnabled,
                breedingRequiresHappiness,
                breedingGenderEnabled,
                traitsEnabled,
                levelingEnabled,
                talentsEnabled,
                reviveSystemEnabled,
                recallTeleportingEnabled,
                telemetryEnabled,
                telemetryBreadcrumbsEnabled,
                animalAgingMode.toConfigValue(),
                animalOldAgeDeathEnabled,
                commandPanelCardsPerPage
        );
    }

    @Nonnull
    TameworkSettingsValues withExperienceSettings(boolean needsEnabled,
                                                  boolean needsDamageEnabled,
                                                  boolean needsDamageLethal,
                                                  boolean happinessEnabled,
                                                  boolean passiveBreedingEnabled,
                                                  boolean breedingRequiresHappiness,
                                                  boolean breedingGenderEnabled,
                                                  boolean traitsEnabled,
                                                  boolean levelingEnabled,
                                                  boolean talentsEnabled,
                                                  boolean hardcore,
                                                  @Nonnull AnimalAgingMode agingMode) {
        return new TameworkSettingsValues(
                populationLimitPerPlayerOwnedTotal,
                populationPerPlayerLimitScope,
                simpleClaimsEnabled,
                simpleClaimsLimitPerClaimChunk,
                simpleClaimsLimitPerClaimTotal,
                simpleClaimsBreedingRequiresClaim,
                simpleClaimsProtectTamedFromNonMembers,
                blockOwnerDamage,
                blockAllPlayerDamageIfOwned,
                invulnerableIfOwned,
                captureClearsOwner,
                spawnSetsOwner,
                captureRequiresOwner,
                spawnRequiresOwner,
                interactionRequiresOwner,
                linkingRequiresOwner,
                needsEnabled,
                needsResourceMode,
                needsDamageEnabled,
                TwNeedsConfig.TickPolicyMode.OWNER_ONLINE_GRACE_THEN_DECAY,
                72.0,
                1.0,
                TwNeedsConfig.DamageModel.MIN_ONLY_PERCENT,
                TwNeedsConfig.DualNeedRule.USE_HIGHER_ONLY,
                hardcore ? 10.0 : 2.0,
                hardcore ? 15.0 : 3.0,
                needsDamageLethal,
                happinessEnabled,
                passiveBreedingEnabled,
                breedingRequiresHappiness,
                breedingGenderEnabled,
                traitsEnabled,
                levelingEnabled,
                talentsEnabled,
                !hardcore,
                !hardcore,
                telemetryEnabled,
                telemetryBreadcrumbsEnabled,
                agingMode,
                hardcore,
                announcementsEnabled,
                commandPanelCardsPerPage
        );
    }

    @Nonnull
    static TameworkSettingsValues fromRuntime() {
        return fromRuntime(true);
    }

    @Nonnull
    static TameworkSettingsValues fromRuntime(boolean announcementsEnabled) {
        return fromResolvedSettings(TameworkSettingsStore.loadRuntimeGlobalSettings(), announcementsEnabled);
    }

    @Nonnull
    private static TameworkSettingsValues fromResolvedSettings(@Nonnull ResolvedTameworkSettings settings, boolean announcementsEnabled) {
        return new TameworkSettingsValues(
                settings.populationLimitPerPlayerOwnedTotal(),
                TwGlobalConfig.PerPlayerLimitScope.fromConfigValue(settings.populationPerPlayerLimitScope()),
                settings.simpleClaimsEnabled(),
                settings.simpleClaimsLimitPerClaimChunk(),
                settings.simpleClaimsLimitPerClaimTotal(),
                settings.simpleClaimsBreedingRequiresClaim(),
                settings.simpleClaimsProtectTamedFromNonMembers(),
                settings.blockOwnerDamage(),
                settings.blockAllPlayerDamageIfOwned(),
                settings.invulnerableIfOwned(),
                settings.captureClearsOwner(),
                settings.spawnSetsOwner(),
                settings.captureRequiresOwner(),
                settings.spawnRequiresOwner(),
                settings.interactionRequiresOwner(),
                settings.linkingRequiresOwner(),
                settings.needsEnabled(),
                settings.needsResourceMode(),
                settings.needsDamageEnabled(),
                TwNeedsConfig.TickPolicyMode.fromConfigValue(settings.needsTickPolicyMode()),
                settings.needsOwnerOfflineGraceHours(),
                settings.needsOwnerOfflineDecayMultiplier(),
                TwNeedsConfig.DamageModel.fromConfigValue(settings.needsDamageModel()),
                TwNeedsConfig.DualNeedRule.fromConfigValue(settings.needsDamageDualNeedRule()),
                settings.needsStarvationDamagePerMinute(),
                settings.needsDehydrationDamagePerMinute(),
                settings.needsDamageLethal(),
                settings.happinessEnabled(),
                settings.passiveBreedingEnabled(),
                settings.breedingRequiresHappiness(),
                settings.breedingGenderEnabled(),
                settings.traitsEnabled(),
                settings.levelingEnabled(),
                settings.talentsEnabled(),
                settings.reviveSystemEnabled(),
                settings.recallTeleportingEnabled(),
                settings.telemetryEnabled(),
                settings.telemetryBreadcrumbsEnabled(),
                AnimalAgingMode.fromConfigValue(settings.animalAgingMode()),
                settings.animalOldAgeDeathEnabled(),
                announcementsEnabled,
                settings.commandPanelCardsPerPage()
        );
    }
}
