param(
    [string] $Root = (Get-Location).Path,
    [string] $Output = "docs/agents/generated-index.md",
    [switch] $Check
)

$ErrorActionPreference = "Stop"

function Get-RepoPath([string] $Path) {
    $relative = [System.IO.Path]::GetRelativePath($script:RepoRoot, (Resolve-Path $Path).Path)
    return $relative -replace "\\", "/"
}

function Get-Files([string] $Path, [string] $Filter = "*") {
    if (-not (Test-Path $Path)) {
        return @()
    }
    return @(Get-ChildItem -LiteralPath $Path -Recurse -File -Filter $Filter |
        Where-Object {
            $_.Extension -ne ".pyc" -and
            $_.FullName -notmatch "[\\/]__pycache__[\\/]"
        })
}

function Add-Section([System.Collections.Generic.List[string]] $Lines, [string] $Title) {
    $Lines.Add("")
    $Lines.Add("## $Title")
    $Lines.Add("")
}

function Add-TableRows(
    [System.Collections.Generic.List[string]] $Lines,
    [array] $Rows,
    [string[]] $Headers,
    [scriptblock] $Renderer
) {
    $Lines.Add("| " + ($Headers -join " | ") + " |")
    $Lines.Add("| " + (($Headers | ForEach-Object { "---" }) -join " | ") + " |")
    foreach ($row in $Rows) {
        $Lines.Add((& $Renderer $row))
    }
}

$script:RepoRoot = (Resolve-Path $Root).Path
$outputPath = Join-Path $script:RepoRoot $Output

$javaFiles = Get-Files (Join-Path $script:RepoRoot "src/main/java") "*.java"
$testFiles = Get-Files (Join-Path $script:RepoRoot "src/test/java") "*.java"
$resourceFiles = Get-Files (Join-Path $script:RepoRoot "src/main/resources")
$toolFiles = Get-Files (Join-Path $script:RepoRoot "scripts/tools")

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("# Generated Agent Index")
$lines.Add("")
$lines.Add('Navigation snapshot generated by `scripts/tools/build-agent-index.ps1`. Do not edit it by hand. Refresh when layout changes affect navigation; ordinary behavior edits do not require regeneration.')

Add-Section $lines "Top Java Packages"
$packageRows = $javaFiles |
    ForEach-Object {
        $relative = Get-RepoPath $_.FullName
        $package = (Split-Path $relative -Parent) -replace "\\", "/"
        [pscustomobject]@{ Package = $package; File = $relative }
    } |
    Group-Object Package |
    Sort-Object @{ Expression = "Count"; Descending = $true }, Name |
    Select-Object -First 30

Add-TableRows $lines $packageRows @("Package", "Files") {
    param($row)
    '| `{0}` | {1} |' -f $row.Name, $row.Count
}

Add-Section $lines "Config Asset Classes"
$configRows = $javaFiles |
    Where-Object { $_.Name -like "Tw*Config*.java" } |
    Sort-Object Name |
    ForEach-Object {
        [pscustomobject]@{ Name = $_.Name; Path = Get-RepoPath $_.FullName }
    }
Add-TableRows $lines $configRows @("Class", "Path") {
    param($row)
    '| `{0}` | `{1}` |' -f $row.Name, $row.Path
}

Add-Section $lines "Architecture And Guard Tests"
$guardRows = $testFiles |
    Where-Object { $_.FullName -match "\\architecture\\" -or $_.Name -match "Guard|Safety" } |
    Sort-Object Name |
    ForEach-Object {
        [pscustomobject]@{ Test = $_.Name; Path = Get-RepoPath $_.FullName }
    }
Add-TableRows $lines $guardRows @("Test", "Path") {
    param($row)
    '| `{0}` | `{1}` |' -f $row.Test, $row.Path
}

Add-Section $lines "Resource Top-Level Areas"
$resourceRows = $resourceFiles |
    ForEach-Object {
        $relative = Get-RepoPath $_.FullName
        $parts = $relative -split "/"
        $area = if ($parts.Count -ge 4) { "$($parts[0])/$($parts[1])/$($parts[2])/$($parts[3])" } else { (Split-Path $relative -Parent) -replace "\\", "/" }
        [pscustomobject]@{ Area = $area }
    } |
    Group-Object Area |
    Sort-Object @{ Expression = "Count"; Descending = $true }, Name |
    Select-Object -First 40
Add-TableRows $lines $resourceRows @("Area", "Files") {
    param($row)
    '| `{0}` | {1} |' -f $row.Name, $row.Count
}

Add-Section $lines "Primary Docs"
$primaryDocCandidates = @(
    "AGENTS.md",
    "README.md",
    "CHANGELOG.md",
    "docs/Architecture.md",
    "docs/Interactions.md",
    "docs/Command-Items.md",
    "docs/Actions-Sensors-Components.md",
    "docs/Build-and-Packaging.md",
    "docs/agents/agent-map.md",
    "docs/agents/guardrails.md",
    "docs/agents/runtime-vs-source-checklist.md",
    "docs/agents/lessons-index.md"
)
# AGENTS.md is required policy but may be supplied outside Git in isolated worktrees.
# Keep the generated index stable whether that external file is currently present or not.
$primaryDocs = $primaryDocCandidates | Where-Object {
    $_ -eq "AGENTS.md" -or (Test-Path (Join-Path $script:RepoRoot $_))
}
foreach ($doc in $primaryDocs) {
    $lines.Add(('- `{0}`' -f $doc))
}

Add-Section $lines "Release Scripts"
$releaseRows = Get-Files (Join-Path $script:RepoRoot "scripts/release") "*.ps1" |
    Sort-Object Name |
    ForEach-Object { [pscustomobject]@{ Script = $_.Name; Path = Get-RepoPath $_.FullName } }
Add-TableRows $lines $releaseRows @("Script", "Path") {
    param($row)
    '| `{0}` | `{1}` |' -f $row.Script, $row.Path
}

Add-Section $lines "Tool Scripts"
$toolRows = $toolFiles |
    Sort-Object FullName |
    Select-Object -First 40 |
    ForEach-Object { [pscustomobject]@{ Tool = $_.Name; Path = Get-RepoPath $_.FullName } }
Add-TableRows $lines $toolRows @("Tool", "Path") {
    param($row)
    '| `{0}` | `{1}` |' -f $row.Tool, $row.Path
}

$content = ($lines -join [Environment]::NewLine) + [Environment]::NewLine

if ($Check) {
    if (-not (Test-Path $outputPath)) {
        throw "Generated index is missing: $Output"
    }
    $existing = Get-Content -LiteralPath $outputPath -Raw
    if ($existing -ne $content) {
        throw "Generated index is stale. Run scripts/tools/build-agent-index.ps1."
    }
    Write-Host "Generated agent index is current."
    exit 0
}

$outputDirectory = Split-Path $outputPath -Parent
if (-not (Test-Path $outputDirectory)) {
    New-Item -ItemType Directory -Path $outputDirectory | Out-Null
}

Set-Content -LiteralPath $outputPath -Value $content -NoNewline
Write-Host "Wrote $Output"
