package com.alechilles.alecstamework.api;

public enum TameworkConfigFamily {
    GLOBAL,
    INTERACTION,
    MOUNTED_GLIDE,
    MOUNTED_DESCENT,
    AVATAR_FLIGHT,
    COMPANION,
    SPAWNER,
    NAME_ITEM,
    NAMES,
    COMMAND_ITEM,
    COOP,
    FOOD,
    HAPPINESS,
    NEEDS,
    BREEDING,
    ATTACHMENT_MIGRATION,
    ATTACHMENT_DISPLAY,
    DYNAMIC_ATTACHMENTS,
    COMPANION_MOVEMENT,
    LEVELING,
    TRAIT,
    TALENT,
    DEBUG,
    CAPTURE_POLICY,
    POPULATION_GROUP,
    MANAGED_ACTIVITY
}

